
// The published API surface. `route` has to match a real handler on disk —
// test/api-docs-check.mjs reads the routes and fails when the two disagree,
// which is what stops this drifting away from the code.
//
// To add an endpoint: write the handler, then add a line here. The check will
// tell you if you forget.
export interface ApiEndpoint {
  route: string
  group: ApiGroup
  auth: 'none' | 'session' | 'token' | 'admin'
  summary: string
}

export const API_GROUPS = [
  'catalog', 'projects', 'collections', 'social', 'account', 'oauth', 'compat',
] as const

export type ApiGroup = typeof API_GROUPS[number]

export const API_ENDPOINTS: ApiEndpoint[] = [
  { route: 'GET /api/catalog/search', group: 'catalog', auth: 'none', summary: 'Search projects, with filters and sorting' },
  { route: 'GET /api/catalog/facets', group: 'catalog', auth: 'none', summary: 'Counts per filter value for the current search' },
  { route: 'GET /api/catalog/gate', group: 'catalog', auth: 'none', summary: 'Whether the catalog is open to everyone yet' },
  { route: 'GET /api/catalog/project/{slug}', group: 'catalog', auth: 'none', summary: 'One project with its versions and files' },
  { route: 'GET /api/catalog/project/{slug}/versions', group: 'catalog', auth: 'none', summary: 'Versions of a project' },
  { route: 'GET /api/catalog/download/{fileId}', group: 'catalog', auth: 'none', summary: 'Download a file and count the download' },
  { route: 'POST /api/catalog/project/{slug}/follow', group: 'projects', auth: 'session', summary: 'Follow a project' },
  { route: 'DELETE /api/catalog/project/{slug}/follow', group: 'projects', auth: 'session', summary: 'Stop following a project' },
  { route: 'POST /api/catalog/project/{slug}/favourite', group: 'projects', auth: 'session', summary: 'Put a project on your favourites shelf' },
  { route: 'DELETE /api/catalog/project/{slug}/favourite', group: 'projects', auth: 'session', summary: 'Take it off the shelf' },
  { route: 'GET /api/catalog/project/{slug}/comments', group: 'projects', auth: 'none', summary: 'Comments on a project' },
  { route: 'POST /api/catalog/project/{slug}/comments', group: 'projects', auth: 'session', summary: 'Write a comment or a reply' },
  { route: 'DELETE /api/catalog/comment/{id}', group: 'projects', auth: 'session', summary: 'Delete your comment, or hide one as a moderator' },
  { route: 'POST /api/catalog/project/{slug}/buy', group: 'projects', auth: 'session', summary: 'Start a checkout for a paid project' },
  { route: 'GET /api/catalog/project/{slug}/thread', group: 'projects', auth: 'session', summary: 'The moderation thread, for authors and moderators' },
  { route: 'POST /api/catalog/project/{slug}/thread', group: 'projects', auth: 'session', summary: 'Reply in the moderation thread, or appeal' },
  { route: 'POST /api/catalog/project/{slug}/submit', group: 'projects', auth: 'session', summary: 'Submit a project for review' },
  { route: 'GET /api/catalog/project/{slug}/members', group: 'projects', auth: 'session', summary: 'Who may work on this project' },
  { route: 'POST /api/catalog/project/{slug}/members', group: 'projects', auth: 'session', summary: 'Add somebody, or change their permissions' },
  { route: 'DELETE /api/catalog/project/{slug}/members/{userId}', group: 'projects', auth: 'session', summary: 'Remove somebody from a project' },
  { route: 'GET /api/catalog/me/projects', group: 'projects', auth: 'session', summary: 'Projects you own or help with' },
  { route: 'GET /api/catalog/me/organizations', group: 'projects', auth: 'session', summary: 'Organizations you belong to' },
  { route: 'GET /api/catalog/me/analytics', group: 'projects', auth: 'session', summary: 'Views and downloads for your projects' },
  { route: 'GET /api/catalog/me/revenue', group: 'projects', auth: 'session', summary: 'Sales of your projects' },
  { route: 'GET /api/catalog/library', group: 'projects', auth: 'session', summary: 'Projects you have bought' },
  { route: 'POST /api/catalog/projects', group: 'projects', auth: 'session', summary: 'Start a project' },
  { route: 'GET /api/catalog/collections', group: 'collections', auth: 'session', summary: 'Your collections, and which hold a given project' },
  { route: 'POST /api/catalog/collections', group: 'collections', auth: 'session', summary: 'Create a collection' },
  { route: 'GET /api/catalog/collections/{id}', group: 'collections', auth: 'none', summary: 'One collection and its projects' },
  { route: 'PATCH /api/catalog/collections/{id}', group: 'collections', auth: 'session', summary: 'Rename a collection or change its visibility' },
  { route: 'DELETE /api/catalog/collections/{id}', group: 'collections', auth: 'session', summary: 'Delete a collection' },
  { route: 'POST /api/catalog/collections/{id}/projects', group: 'collections', auth: 'session', summary: 'Put a project into a collection' },
  { route: 'DELETE /api/catalog/collections/{id}/projects', group: 'collections', auth: 'session', summary: 'Take a project out of a collection' },
  { route: 'POST /api/catalog/reports', group: 'catalog', auth: 'session', summary: 'Report a project, comment, user or organization' },
  { route: 'GET /api/catalog/reports', group: 'catalog', auth: 'session', summary: 'Reports you have filed' },
  { route: 'GET /api/catalog/reports/{id}/thread', group: 'catalog', auth: 'session', summary: 'The conversation about one report' },
  { route: 'POST /api/catalog/reports/{id}/thread', group: 'catalog', auth: 'session', summary: 'Reply about a report' },
  { route: 'GET /api/org/{slug}', group: 'projects', auth: 'none', summary: 'An organization, its members and its projects' },
  { route: 'PATCH /api/org/{slug}', group: 'projects', auth: 'session', summary: 'Edit an organization' },
  { route: 'POST /api/org/{slug}/logo', group: 'projects', auth: 'session', summary: 'Upload an organization logo' },
  { route: 'POST /api/org/{slug}/invite', group: 'projects', auth: 'session', summary: 'Invite somebody to an organization' },
  { route: 'POST /api/org/{slug}/leave', group: 'projects', auth: 'session', summary: 'Leave an organization' },
  { route: 'PATCH /api/org/{slug}/members/{userId}', group: 'projects', auth: 'session', summary: 'Change a member role or permissions' },
  { route: 'DELETE /api/org/{slug}/members/{userId}', group: 'projects', auth: 'session', summary: 'Remove a member' },
  { route: 'GET /api/org/mine', group: 'projects', auth: 'session', summary: 'Organizations you belong to' },
  { route: 'GET /api/seller/status', group: 'account', auth: 'session', summary: 'Whether your payout accounts are ready' },
  { route: 'POST /api/seller/onboard', group: 'account', auth: 'session', summary: 'Start or resume Stripe onboarding' },
  { route: 'GET /api/seller/ledger', group: 'account', auth: 'session', summary: 'Your balance, ledger entries and payouts' },
  { route: 'POST /api/seller/payout', group: 'account', auth: 'session', summary: 'Request a payout' },
  { route: 'POST /api/verification', group: 'account', auth: 'session', summary: 'Apply to be a partner or a verified organization' },
  { route: 'GET /api/verification/mine', group: 'account', auth: 'session', summary: 'Your verification applications' },
  { route: 'DELETE /api/verification/{id}', group: 'account', auth: 'session', summary: 'Withdraw an application' },
  { route: 'GET /api/u/{username}', group: 'account', auth: 'none', summary: 'A public profile' },
  { route: 'GET /api/users', group: 'social', auth: 'session', summary: 'Search people by name' },
  { route: 'PATCH /api/me/profile', group: 'account', auth: 'session', summary: 'Change your bio and links' },
  { route: 'POST /api/me/avatar', group: 'account', auth: 'session', summary: 'Upload an avatar' },
  { route: 'PATCH /api/me/locale', group: 'account', auth: 'session', summary: 'Set your language' },
  { route: 'GET /api/me/notifications', group: 'account', auth: 'session', summary: 'Your notification preferences' },
  { route: 'PATCH /api/me/notifications', group: 'account', auth: 'session', summary: 'Change which notifications reach you, and how' },
  { route: 'GET /api/me/limits', group: 'account', auth: 'session', summary: 'How much of each account limit you have used' },
  { route: 'GET /api/me/blocks', group: 'account', auth: 'session', summary: 'People you have blocked' },
  { route: 'POST /api/me/blocks', group: 'account', auth: 'session', summary: 'Block somebody' },
  { route: 'DELETE /api/me/blocks/{id}', group: 'account', auth: 'session', summary: 'Unblock somebody' },
  { route: 'GET /api/me/close', group: 'account', auth: 'session', summary: 'What deleting your account would remove' },
  { route: 'POST /api/me/close', group: 'account', auth: 'session', summary: 'Delete your account' },
  { route: 'POST /api/me/minecraft', group: 'account', auth: 'session', summary: 'Link a Minecraft account' },
  { route: 'POST /api/me/activity', group: 'account', auth: 'session', summary: 'Record play time from the launcher' },
  { route: 'GET /api/me/tokens', group: 'oauth', auth: 'session', summary: 'Your personal access tokens' },
  { route: 'POST /api/me/tokens', group: 'oauth', auth: 'session', summary: 'Create a token; the secret is shown once' },
  { route: 'DELETE /api/me/tokens/{id}', group: 'oauth', auth: 'session', summary: 'Revoke a token' },
  { route: 'GET /api/me/oauth-clients', group: 'oauth', auth: 'session', summary: 'Applications you registered' },
  { route: 'POST /api/me/oauth-clients', group: 'oauth', auth: 'session', summary: 'Register an application' },
  { route: 'PATCH /api/me/oauth-clients/{id}', group: 'oauth', auth: 'session', summary: 'Edit an application' },
  { route: 'DELETE /api/me/oauth-clients/{id}', group: 'oauth', auth: 'session', summary: 'Delete an application' },
  { route: 'POST /api/me/oauth-clients/{id}/secret', group: 'oauth', auth: 'session', summary: 'Rotate an application secret' },
  { route: 'GET /api/me/authorizations', group: 'oauth', auth: 'session', summary: 'Applications you gave access to' },
  { route: 'DELETE /api/me/authorizations/{id}', group: 'oauth', auth: 'session', summary: 'Withdraw an application access and its tokens' },
  { route: 'GET /api/oauth/authorize', group: 'oauth', auth: 'session', summary: 'What an application is asking for' },
  { route: 'POST /api/oauth/authorize', group: 'oauth', auth: 'session', summary: 'Approve or refuse, and get the redirect back' },
  { route: 'POST /api/oauth/token', group: 'oauth', auth: 'none', summary: 'Exchange an authorization code for a token' },
  { route: 'GET /api/friends', group: 'social', auth: 'session', summary: 'Your friends and pending requests' },
  { route: 'POST /api/friends', group: 'social', auth: 'session', summary: 'Send a friend request' },
  { route: 'PATCH /api/friends/{id}', group: 'social', auth: 'session', summary: 'Accept or refuse a request' },
  { route: 'DELETE /api/friends/{id}', group: 'social', auth: 'session', summary: 'Remove a friend' },
  { route: 'POST /api/presence', group: 'social', auth: 'session', summary: 'Report that you are online or playing' },
  { route: 'GET /api/notifications', group: 'social', auth: 'session', summary: 'Your notifications' },
  { route: 'POST /api/notifications/read', group: 'social', auth: 'session', summary: 'Mark notifications read' },
  { route: 'DELETE /api/notifications/{id}', group: 'social', auth: 'session', summary: 'Dismiss a notification' },
  { route: 'GET /api/shares', group: 'social', auth: 'session', summary: 'Modpacks you have shared' },
  { route: 'POST /api/share', group: 'social', auth: 'session', summary: 'Create a share code for an instance' },
  { route: 'POST /api/share/upload-url', group: 'social', auth: 'session', summary: 'Get an upload address for the pack' },
  { route: 'GET /api/share/{code}', group: 'social', auth: 'none', summary: 'What is behind a share code' },
  { route: 'DELETE /api/share/{code}', group: 'social', auth: 'session', summary: 'Revoke a share' },
  { route: 'POST /api/share/{code}/complete', group: 'social', auth: 'session', summary: 'Finish an upload' },
  { route: 'POST /api/share/{code}/extend', group: 'social', auth: 'session', summary: 'Push back the expiry' },
  { route: 'POST /api/share/{code}/invite', group: 'social', auth: 'session', summary: 'Send a share to a friend' },
  { route: 'DELETE /api/share/{code}/invite', group: 'social', auth: 'session', summary: 'Take back an invitation' },
  { route: 'GET /api/v2/projects', group: 'compat', auth: 'none', summary: 'Modrinth-compatible project search' },
  { route: 'GET /api/v2/project/{id}', group: 'compat', auth: 'none', summary: 'Modrinth-compatible project' },
  { route: 'GET /api/v2/project/{id}/version', group: 'compat', auth: 'none', summary: 'Modrinth-compatible version list' },
  { route: 'GET /api/v2/version/{id}', group: 'compat', auth: 'none', summary: 'Modrinth-compatible version' },
  { route: 'GET /api/v2/version_file/{hash}', group: 'compat', auth: 'none', summary: 'Find a version by file hash' },
  { route: 'POST /api/v2/version_files', group: 'compat', auth: 'none', summary: 'Find many versions by hash in one request' },
  { route: 'OPTIONS /api/v2/version_files', group: 'compat', auth: 'none', summary: 'CORS preflight for the bulk hash lookup' },
  { route: 'GET /api/curseforge/{path}', group: 'compat', auth: 'none', summary: 'Proxy to CurseForge, so a key is not shipped in a client' },
  { route: 'GET /api/mc-profile', group: 'compat', auth: 'none', summary: 'A Minecraft profile by name or UUID' },
  { route: 'GET /api/mc-skin', group: 'compat', auth: 'none', summary: 'A Minecraft skin texture' },
  { route: 'GET /api/mc-cape', group: 'compat', auth: 'none', summary: 'A Minecraft cape texture' },
  { route: 'GET /api/mc-capes', group: 'compat', auth: 'none', summary: 'Every cape a profile has' },
  { route: 'GET /api/badges', group: 'account', auth: 'none', summary: 'Badges that can be awarded' },
  { route: 'GET /api/badges/{slug}', group: 'account', auth: 'none', summary: 'One badge' },
  { route: 'GET /api/version', group: 'compat', auth: 'none', summary: 'Latest launcher release, for the updater' },
  { route: 'POST /api/secret', group: 'account', auth: 'session', summary: 'Redeem a code' },
  { route: 'GET /api/auth-providers', group: 'account', auth: 'none', summary: 'Which sign-in providers are configured' },
]

export function endpointsIn(group: ApiGroup): ApiEndpoint[] {
  return API_ENDPOINTS.filter(endpoint => endpoint.group === group)
}
